name: Java Unit Test and Analysis with SonarCloud
description: Run Java unit tests, can analyse with SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run tests, start with '|' for multi-line
    required: true

  dir:
    description: App/package directory
    required: true

  java-version:
    description: Java version, defaults to 17 (LTS)
    required: true

  ### Typical / recommended
  java-cache:
    description: Java package manager cache, defaults to maven
    default: maven

  java-distribution:
    description: Java distribution, defaults to temurin
    default: temurin

  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}

  sonar_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)

  triggers:
    description: Paths (array) used to trigger a build; e.g. ('./backend/' './frontend/)

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}

  repository:
    description: Non-default repository to clone (used for testing this action)
    default: ${{ github.repository }}

  branch:
    description: Non-default branch to clone (used for testing this action)
    default: ""

  triggers_event:
    description: Events (array) to use with triggers; e.g. ("pull_request" "push" "workflow_dispatch")
    default: "('pull_request')"

runs:
  using: composite
  steps:
    - name: Warnings for breaking changes
      shell: bash
      run: |
        # Warnings for breaking changes

        # sonar_project_token renamed sonar_token
        if [ ! -z "${{ inputs.sonar_project_token }}" ]; then
          echo -e "\nsonar_project_token renamed.  Please correct this and try again."
          echo -e "\n\tAction: rename sonar_project_token to sonar_token\n"
          exit 1
        fi

    # Send triggers to diff action
    - id: diff
      uses: bcgov-nr/action-diff-triggers@v0.2.0
      with:
        triggers: ${{ inputs.triggers }}
        diff_branch: ${{ inputs.diff_branch }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}

    # Setup Java and cache dir
    - uses: actions/setup-java@v4
      with:
        cache: ${{ inputs.java-cache }}
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        server-id: 'github'

    # Run tests, hopefully generating coverage for SonarCloud
    - name: Run Tests
      if: steps.diff.outputs.triggered == 'true'
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        # Run tests
        ${{ inputs.commands }}

    ### Optional SonarCloud

    - if: inputs.sonar_token && steps.diff.outputs.triggered == 'true'
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        # Run SonarCloud for ${{ inputs.java-cache }}

        # if [ "${{ inputs.java-cache }}" == "maven" ]; then
        #   SONAR_CMD="mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"
        # elif [ "${{ inputs.java-cache }}" == "gradle" ]; then
        #   SONAR_CMD="./gradlew build sonarqube --info"
        # else
        #   echo "ERROR: inputs.java-cache = ${{ inputs.java-cache }}"
        #   exit 1
        # fi

        # "${SONAR_CMD}" -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}

    # ### Cleanup

    # # Fix - Docker can take file ownership, causing a cleanup fail
    # - shell: bash
    #   if: steps.diff.outputs.triggered == 'true'
    #   id: get_uid
    #   run: |
    #     # User for workstation ownership reset/fix
    #     echo "uid=$(id -u ${USER})" >> $GITHUB_OUTPUT
    # - uses: peter-murray/reset-workspace-ownership-action@v1
    #   if: steps.diff.outputs.triggered == 'true'
    #   with:
    #     user_id: ${{ steps.get_uid.outputs.uid }}

    # # Fix - Clone for action.yml and other verifications
    # - name: Checkout Action repo to pass tests
    #   if: always() && inputs.repository != github.repository
    #   uses: actions/checkout@v4
